name: Test mdp-toolkit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        extras: ["", "[joblib,scikit-learn,scipy,libsvm,pytest]"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install cython3 gfortran libblas-dev liblapack-dev
        python -m pip install --upgrade pip
        python -m pip install pytest-cov
        python -m pip install -e .${{ matrix.extras }}
    - name: Test with pytest
      run: |
        python -m pytest --cov-config=.coveragerc --cov=mdp --seed=725021957 mdp
        python -m pytest --cov-config=.coveragerc --cov=bimdp --cov-append --seed=725021957 bimdp
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

    - name: Upload coverage data to coveralls.io
      uses: AndreMiras/coveralls-python-action@develop
      if: runner.os == 'Linux' # Only works on Linux
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.os }}-py-${{ matrix.python-version }}-${{ matrix.extras }}
        parallel: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true

