name: Test mdp-toolkit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
        extras: ["", "[joblib,scikit-learn,scipy,libsvm,pytest]"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install cython3 gfortran libblas-dev liblapack-dev
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .${{ matrix.extras }}
    - name: Test with pytest
      run: |
        python -m pytest --seed=725021957 mdp
        python -m pytest --seed=725021957 bimdp
